#---------springboot配置信息---------
server: 
    port: 8080
#---------mysql数据库配置信息---------
spring: 
    datasource:
        name: myDataSource
        type: com.alibaba.druid.pool.DruidDataSource  
        url: jdbc:mysql://192.168.31.32:3306/yc_test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
        username: root
        password: root
        driverClassName: com.mysql.jdbc.Driver
#---------druid连接池的配置信息 ---------
        initialSize: 50  
        minIdle: 50  
        maxActive: 50  
        maxWait: 60000  
        timeBetweenEvictionRunsMillis: 60000  
        minEvictableIdleTimeMillis: 300000  
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true  
        testOnBorrow: false  
        testOnReturn: false  
        poolPreparedStatements: true  
        maxPoolPreparedStatementPerConnectionSize: 20  
        filters: stat,wall,log4j  
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#---------模板引擎thymeleaf-----------
    thymeleaf: 
        cache: false
        prefix: classpath:/templates/
        suffix: .html
        encoding: UTF-8
        content-type: text/html
        mode: HTML5
#---------Elastic的配置信息-----------
elastic:
    server:
        host: 192.168.31.33                             #es服务器ip
        port: 9300                                      #es服务监听端口
        clusterName: escluster                          #es服务集群名称
    client:
        pool: 
            initialSize: 10
            maxSize: 20
            minSize: 8
            maxWait: 6000
        import:
            index: logindex                             #es服务器导入目标索引库
            type: systemlog                             #es服务器导入目标索引库类型
            bulkSize: 2000                              #每批提交到es导入的文档数
#---------数据迁移线程池信息-----------
#mysql数据库迁移数据表
trans:
    datasource:
        table:
            name: log                                   #mysql迁移目标表名
            fetchSize: 10000                            #mysql数据库单次抓取数目  
    thread:
        pool:
            size: 10                                    #数据迁移线程池容量（决定任务迁移拆分线程数据/任务数目）
#mybatis集成配置
mybatis: 
    mapperLocations: classpath:mapper/*.xml             #mapper.xml文件路径
    typeAliasesPackage: com.data.trans.model            #mybatis数据模型实体包路径
    config: mybatis-config.xml                          #mybatis配置文件的路径